### ISSUE TITLE
normalizeInterval should be improved

### ISSUE THREAD

**Issue by nyamsprod** [jeromegamez/duration-php#3]
https://github.com/jeromegamez/duration-php/blob/67abef88a064f6b79a02fd769d618b99df34b5d7/src/Duration.php#L149

This method should be improved to guard against DST and other timezone shenanigans...

```php
        $now = new DateTimeImmutable();
        $then = $now->add($value);
        return $now->diff($then);
``` 

should be

```php
        $now = new DateTimeImmutable('@'.time());
        $then = $now->add($value);
        return $now->diff($then);
``` 

this way your reference DateTimeImmutable object is created against a timestamp (aka) GMT which is not affected by Timezone trickery 😉 .

Maybe refactor your code to always use this code everywhere instead of repeating it everywhere it would make the code more maintainable too. If I'm correct this pattern is used in many places currently.

PS: if you are lazy .. you could even use `DateTimeImmutable('@0')` as a private static variable 👍  anyway this part should be improved.

**Comment by nyamsprod** [comment]
of course this refactoring can only be done once your class is made final #2

**Comment by jeromegamez** [comment]
Thanks again! New release incoming :)
